spring:
  application:
    name: identity-service

  datasource:
    # Khi chạy local: dùng localhost
    # Khi chạy trong Docker: ghi đè bằng biến môi trường DB_HOST=db
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:book_ecommerce}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # create | create-drop | update | validate | none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /identity

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  otlp:
    tracing:
      endpoint: http://${OTEL_EXPORTER_OTLP_ENDPOINT:localhost}:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
