spring:
  application:
    name: identity-service

  # Profile mặc định khi không set gì = local dev
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /identity

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
