### Create User
POST http://localhost:8080/identity/users
Content-Type: application/json

{
  "username": "thinhnguyen4",
  "password": "secretpassword",
  "firstName": "Thinh",
  "lastName": "Nguyen",
  "dob": "1995-01-01"
}
